function_names = [
    '__ZN8CryptoPP21InvertibleRSAFunction10InitializeERKNS_7IntegerES3_S3_',
    '__ZThn120_NK8CryptoPP21InvertibleRSAFunction16CalculateInverseERNS_21RandomNumberGeneratorERKNS_7IntegerE',
    '__ZNK8CryptoPP21InvertibleRSAFunction16CalculateInverseERNS_21RandomNumberGeneratorERKNS_7IntegerE',
    '__ZNK8CryptoPP25InvertibleRSAFunction_ISO16CalculateInverseERNS_21RandomNumberGeneratorERKNS_7IntegerE',
    '__ZThn120_NK8CryptoPP25InvertibleRSAFunction_ISO16CalculateInverseERNS_21RandomNumberGeneratorERKNS_7IntegerE',
    '__ZN8CryptoPP25GeneratableCryptoMaterial14GenerateRandomERNS_21RandomNumberGeneratorERKNS_14NameValuePairsE',
    '__ZThn136_N8CryptoPP21InvertibleRSAFunction14GenerateRandomERNS_21RandomNumberGeneratorERKNS_14NameValuePairsE',
    '__ZN8CryptoPP21InvertibleRSAFunction14GenerateRandomERNS_21RandomNumberGeneratorERKNS_14NameValuePairsE',
]
