function_names = [
    '_crypto_aead_aes256gcm_encrypt_detached',
    '_crypto_aead_aes256gcm_encrypt',
    '_crypto_aead_aes256gcm_decrypt_detached',
    '_crypto_aead_aes256gcm_decrypt',
    '_crypto_aead_aes256gcm_beforenm',
    '_crypto_aead_aes256gcm_encrypt_detached_afternm',
    '_crypto_aead_aes256gcm_encrypt_afternm',
    '_crypto_aead_aes256gcm_decrypt_detached_afternm',
    '_crypto_aead_aes256gcm_decrypt_afternm',
    '_crypto_aead_aes256gcm_is_available',
    '_crypto_aead_aes256gcm_keybytes',
    '_crypto_aead_aes256gcm_nsecbytes',
    '_crypto_aead_aes256gcm_npubbytes',
    '_crypto_aead_aes256gcm_abytes',
    '_crypto_aead_aes256gcm_statebytes',
    '_crypto_aead_aes256gcm_messagebytes_max',
    '_crypto_aead_aes256gcm_keygen'
]
