
# (C) 2015,2016,2017,2019,2020,2021 Jack Lloyd
# (C) 2015,2016 Simon Warta
# Botan is released under the Simplified BSD License (see license.txt)

clone_depth: 5

environment:
  SCCACHE_CACHE_SIZE: 320M
  SCCACHE_VERSION: 0.2.15
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

  matrix:

    # MSVC 2019 x86-64 w/debug iterators
    - CC: VC2019
      PLATFORM: x86_amd64
      TARGET: sanitizer
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      MAKE_TOOL: jom
      TARGET_CC: msvc

    # MSVC 2019 static x86-64 with Boost
    - CC: VC2019
      PLATFORM: x86_amd64
      TARGET: static
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      BOOST_ROOT: "C:\\Libraries\\boost_1_73_0"
      BOOST_LIBRARYDIR: "C:\\Libraries\\boost_1_73_0\\lib64-msvc-14.2"
      BOOST_SYSTEM_LIBRARY: "libboost_system-vc142-mt-x64-1_73"
      MAKE_TOOL: jom
      TARGET_CC: msvc
      EXTRA_FLAGS: "--extra-cxxflags=/DUNICODE --extra-cxxflags=/D_UNICODE"

    # MSVC 2019 x86-64 preview
    - CC: VC2019p
      PLATFORM: x86_amd64
      TARGET: shared
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019 Preview
      MAKE_TOOL: jom
      TARGET_CC: msvc

    # MinGW GCC
    - CC: MinGW
      PLATFORM: x86_amd64
      TARGET: static
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MAKE_TOOL: mingw32-make
      TARGET_CC: gcc

install:
  - call src\scripts\ci\setup_appveyor.bat

build_script:
  - python src\scripts\ci_build.py --os=windows --cc=%TARGET_CC% --without-python3 --compiler-cache=sccache --make-tool=%MAKE_TOOL% --cpu=%PLATFORM% %EXTRA_FLAGS% %TARGET%

# whitelist branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
    - master
    - release-2

cache:
  - C:\Users\appveyor\AppData\Local\Mozilla\sccache\cache
  - C:\projects\botan\jom.zip
  - C:\projects\botan\sccache-v%SCCACHE_VERSION%-x86_64-pc-windows-msvc.tar.gz
