
# (C) 2015,2016,2017,2019,2020,2021 Jack Lloyd
# (C) 2015,2016 Simon Warta
# Botan is released under the Simplified BSD License (see license.txt)

language: cpp
os: linux
dist: focal
compiler: gcc

jobs:
  include:
    - name: FreeBSD x86_64 (Clang)
      os: freebsd
      compiler: clang
      env:
       - TARGET="shared"

    - name: Linux s390x (GCC)
      arch: s390x
      env:
       - TARGET="shared"

    - name: Linux ppc64le (GCC)
      arch: ppc64le
      env:
       - TARGET="shared"

    - name: Linux arm64 (GCC)
      arch: arm64
      env:
       - TARGET="shared"

    - name: Linux arm32 cross (GCC)
      arch: arm64
      env:
       - TARGET="cross-arm32"

install:
  - ./src/scripts/ci/setup_travis.sh

script:
  - ./src/scripts/ci_build.py --os=$TRAVIS_OS_NAME --cc=$CC --cc-bin=$CXX --without-pylint3 $EXTRA_FLAGS $TARGET

# whitelist branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
    - master
    - release-2
    - coverity_scan

git:
  depth: 10

cache:
  ccache: true

addons:
  coverity_scan:
    project:
      name: "randombit/botan"
    notification_email: jack@randombit.net
    build_command_prepend: "./configure.py --no-optimizations --with-zlib --with-openssl"
    build_command: "make -j2"
    branch_pattern: coverity_scan
