language: c

dist: trusty
sudo: required

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      valgrind
      cloc

install:
  - travis_retry wget https://cmake.org/files/v3.12/cmake-3.12.4-Linux-x86_64.sh
  - sudo bash cmake-3.12.4-Linux-x86_64.sh --skip-license --exclude-subdir --prefix=/usr/local
  - export PATH="/usr/local/bin:$PATH"
  - mkdir -p $HOME/protobuf && pushd $HOME/protobuf
    && wget 'https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip' -O protoc-3.6.1-linux-x86_64.zip
    && unzip protoc-3.6.1-linux-x86_64.zip -d protoc-3.6.1-linux-x86_64
    && wget 'https://github.com/google/protobuf/releases/download/v3.6.1/protobuf-python-3.6.1.tar.gz' -O protobuf-python-3.6.1.tar.gz
    && tar xzf protobuf-python-3.6.1.tar.gz
    && cp protoc-3.6.1-linux-x86_64/bin/protoc protobuf-3.6.1/src/
    && pushd protobuf-3.6.1/python
    && python setup.py build && sudo python setup.py install
    && popd
    && popd

before_script:
  - ${CC} --version
  - cmake --version
  - valgrind --version

script:
  - cmake -H. -Bbuild
      -DENABLE_HEAVY_TESTS=OFF
      -DVIRGIL_C_MT_TESTING=OFF
      -DENABLE_BENCHMARKING=ON
      -DVIRGIL_POST_QUANTUM=ON
      -DVIRGIL_PROGRAMS=ON
  - cmake --build build -- -j8
    && pushd build
    && ctest -T memcheck --output-on-failure
    && popd
  - cmake -H. -Bbuild -DVIRGIL_C_MT_TESTING=ON
  - cmake --build build -- -j8
    && pushd build
    && ctest -L multi-threading --output-on-failure
    && ./benchmarks/foundation/bench
    && popd
  - cat build/Testing/Temporary/MemoryChecker.*.log

after_success:
  - cmake --build build --target cloc
